spring:
  application:
    name: user-service
server:
  port: 9004
eureka:
  instance:
    preferIpAddress: true
    hostname: user-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
