spring:
  application:
    name: discovery-service
server:
  port: 9000
eureka:
  instance:
    preferIpAddress: true
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9000/eureka
